export const DEFAULT_LOAN_INTEREST_RATE = 4.25;
export const MIN_LOAN_INTEREST_RATE = 2;
export const MAX_LOAN_INTEREST_RATE = 10;

export const DEFAULT_DOWNPAYMENT_VALUE = 100;
export const DEFAULT_EST_IMMEDIATE_COSTS_RATE = 2000;

export const MIN_DOWNPAYMENT_VALUE = 20;
export const MAX_DOWNPAYMENT_VALUE = 100;

export const DEFAULT_CLOSING_COST_RATE = 1.5;

export const DEFAULT_APPRECIATION_RATE = 3;
export const MIN_APPRECIATION_RATE = -0.5;
export const MAX_APPRECIATION_RATE = 15;
